name: CI Orchestrator
on:
    pull_request:
        branches: [main]
        paths-ignore:
            - "k8s/**"
permissions:
    contents: read
    packages: write

jobs:
    website-image:
        uses: ./.github/workflows/build-website.yml
    docker:
        uses: ./.github/workflows/docker-image.yml
    linter:
        uses: ./.github/workflows/pylintTelegram.yml
    tests:
        uses: ./.github/workflows/testPythonTelegram.yml
